services:

  ollama:
    image: ollama/ollama
    expose:
     - 11434/tcp
    ports:
     - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434


  ollama-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_URL=http://ollama:11434
    command: tunnel --no-autoupdate
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml
    depends_on:
      - ollama

volumes:
  ollama_data:
  cloudflared: